var searchData=
[
  ['can_20validation_0',['CAN Validation',['../group__dv__can.html',1,'']]],
  ['can_5fcheckinvalidinit_1',['CAN_CheckInvalidInit',['../group__can__tests.html#ga9eb648cf67e1004f73cbd8222a7fe870',1,'DV_CAN.c']]],
  ['can_5fgetcapabilities_2',['CAN_GetCapabilities',['../group__can__tests.html#ga4d770ed38d9ceffea0efa93647ae3bd5',1,'DV_CAN.c']]],
  ['can_5finitialization_3',['CAN_Initialization',['../group__can__tests.html#ga4c93a718e622e8dd98ecdd6f892b793f',1,'DV_CAN.c']]],
  ['can_5floopback_5fcheckbitrate_4',['CAN_Loopback_CheckBitrate',['../group__can__tests.html#ga495f70c896f1720d5ebb7cc716cf06a3',1,'DV_CAN.c']]],
  ['can_5floopback_5fcheckbitratefd_5',['CAN_Loopback_CheckBitrateFD',['../group__can__tests.html#gaf76073c1c77f6633296c33750dac77d1',1,'DV_CAN.c']]],
  ['can_5floopback_5ftransfer_6',['CAN_Loopback_Transfer',['../group__can__tests.html#ga4e4d206b95ce1b46d37c246f20ff9390',1,'DV_CAN.c']]],
  ['can_5floopback_5ftransferfd_7',['CAN_Loopback_TransferFD',['../group__can__tests.html#gad619f0a6a779d4a069d381b95ef60521',1,'DV_CAN.c']]],
  ['can_5fpowercontrol_8',['CAN_PowerControl',['../group__can__tests.html#ga24ea6e524e87e05af02b52f5896f0db7',1,'DV_CAN.c']]],
  ['choose_20strong_20solution_20base_20folder_20strong_20click_20strong_20create_20strong_9',['Step 4: Choose &lt;strong&gt;Solution Base Folder&lt;/strong&gt;, click &lt;strong&gt;Create&lt;/strong&gt;.',['../setup.html#autotoc_md3',1,'']]],
  ['click_20strong_20create_20a_20new_20solution_20strong_10',['Step 1: In the &lt;strong&gt;CMSIS&lt;/strong&gt; extension, click &lt;strong&gt;Create a New Solution&lt;/strong&gt;.',['../setup.html#autotoc_md0',1,'']]],
  ['click_20strong_20create_20strong_11',['Step 4: Choose &lt;strong&gt;Solution Base Folder&lt;/strong&gt;, click &lt;strong&gt;Create&lt;/strong&gt;.',['../setup.html#autotoc_md3',1,'']]],
  ['click_20strong_20ok_20strong_12',['Step 5: Select the &lt;strong&gt;Board Layer&lt;/strong&gt; that provides &lt;strong&gt;required CMSIS Driver&lt;/strong&gt;, click &lt;strong&gt;OK&lt;/strong&gt;.',['../setup.html#autotoc_md4',1,'']]],
  ['click_20strong_20save_20strong_13',['Step 6: In the &lt;strong&gt;Manage Solution&lt;/strong&gt;, under &lt;strong&gt;Build Type&lt;/strong&gt; select desired Driver for validation, click &lt;strong&gt;Save&lt;/strong&gt;.',['../setup.html#autotoc_md5',1,'']]],
  ['closedebug_14',['closeDebug',['../group__framework__funcs.html#gab619c5d0a237afcf7ec113ff7b8c5ced',1,'DV_Framework.c']]],
  ['cmsis_20driver_20strong_20click_20strong_20ok_20strong_15',['Step 5: Select the &lt;strong&gt;Board Layer&lt;/strong&gt; that provides &lt;strong&gt;required CMSIS Driver&lt;/strong&gt;, click &lt;strong&gt;OK&lt;/strong&gt;.',['../setup.html#autotoc_md4',1,'']]],
  ['cmsis_20driver_20validation_20application_20strong_16',['Step 3: Under &lt;strong&gt;Templates, Reference Applications, and Examples&lt;/strong&gt;, select &lt;strong&gt;Driver Validation (CMSIS-Driver Validation application)&lt;/strong&gt;.',['../setup.html#autotoc_md2',1,'']]],
  ['cmsis_20rtos2_17',['CMSIS-RTOS2',['../resource_requirements.html#rtos2_req',1,'']]],
  ['cmsis_20strong_20extension_20click_20strong_20create_20a_20new_20solution_20strong_18',['Step 1: In the &lt;strong&gt;CMSIS&lt;/strong&gt; extension, click &lt;strong&gt;Create a New Solution&lt;/strong&gt;.',['../setup.html#autotoc_md0',1,'']]],
  ['cmsis_5fdv_19',['cmsis_dv',['../group__framework__funcs.html#ga6e9dc1a6a5392afdf07478bd6b159287',1,'DV_Framework.c']]],
  ['commands_20',['Commands',['../group__spi__server.html#spi_server_commands',1,'Commands'],['../group__usart__server.html#usart_server_commands',1,'Commands']]],
  ['communication_20setup_21',['Loopback Communication Setup',['../group__dv__eth.html#autotoc_md10',1,'']]],
  ['compliance_20tests_22',['USB Compliance Tests',['../group__usbd__comp__test.html',1,'']]],
  ['configuration_23',['Configuration',['../group__can__config.html',1,'Configuration'],['../group__eth__config.html',1,'Configuration'],['../group__gpio__config.html',1,'Configuration'],['../group__i2c__config.html',1,'Configuration'],['../group__mci__config.html',1,'Configuration'],['../group__spi__config.html',1,'Configuration'],['../group__usart__config.html',1,'Configuration'],['../group__usbd__config.html',1,'Configuration'],['../group__usbh__config.html',1,'Configuration'],['../group__wifi__config.html',1,'Configuration'],['../group__spi__server.html#spi_server_config',1,'Configuration'],['../group__usart__server.html#usart_server_config',1,'Configuration']]],
  ['configuration_20settings_24',['Configuration settings',['../group__can__config.html#can_config_detail',1,'Configuration settings'],['../group__eth__config.html#eth_config_detail',1,'Configuration settings'],['../group__gpio__config.html#gpio_config_detail',1,'Configuration settings'],['../group__i2c__config.html#i2c_config_detail',1,'Configuration settings'],['../group__mci__config.html#mci_config_detail',1,'Configuration settings'],['../group__spi__config.html#spi_config_detail',1,'Configuration settings'],['../group__spi__server.html#spi_server_config_detail',1,'Configuration settings'],['../group__usart__config.html#usart_config_detail',1,'Configuration settings'],['../group__usart__server.html#usart_server_config_detail',1,'Configuration settings'],['../group__usbd__config.html#usbd_config_detail',1,'Configuration settings'],['../group__usbh__config.html#usbh_config_detail',1,'Configuration settings']]],
  ['configure_20the_20driver_20tests_20in_20appropriate_20strong_20dv_5f_20_5fconfig_20h_20strong_20file_25',['Step 7: Configure the Driver Tests in appropriate &lt;strong&gt;DV_..._Config.h&lt;/strong&gt; file.',['../setup.html#autotoc_md6',1,'']]],
  ['control_26',['Control',['../group__wifi__ctrl.html',1,'']]],
  ['create_20a_20new_20solution_20strong_27',['Step 1: In the &lt;strong&gt;CMSIS&lt;/strong&gt; extension, click &lt;strong&gt;Create a New Solution&lt;/strong&gt;.',['../setup.html#autotoc_md0',1,'']]],
  ['create_20strong_28',['Step 4: Choose &lt;strong&gt;Solution Base Folder&lt;/strong&gt;, click &lt;strong&gt;Create&lt;/strong&gt;.',['../setup.html#autotoc_md3',1,'']]]
];
