var searchData=
[
  ['target_20board_20strong_0',['Step 2: Select the &lt;strong&gt;Target Board&lt;/strong&gt;.',['../setup.html#autotoc_md1',1,'']]],
  ['templates_20reference_20applications_20and_20examples_20strong_20select_20strong_20driver_20validation_20cmsis_20driver_20validation_20application_20strong_1',['Step 3: Under &lt;strong&gt;Templates, Reference Applications, and Examples&lt;/strong&gt;, select &lt;strong&gt;Driver Validation (CMSIS-Driver Validation application)&lt;/strong&gt;.',['../setup.html#autotoc_md2',1,'']]],
  ['test_20mode_20_3a_20b_20loopback_20b_2',['Test Mode : b Loopback b',['../group__dv__spi.html#autotoc_md11',1,'Test Mode : &lt;b&gt;Loopback&lt;/b&gt;'],['../group__dv__usart.html#autotoc_md13',1,'Test Mode : &lt;b&gt;Loopback&lt;/b&gt;']]],
  ['test_20mode_20_3a_20b_20spi_20server_20b_3',['Test Mode : &lt;b&gt;SPI Server&lt;/b&gt;',['../group__dv__spi.html#autotoc_md12',1,'']]],
  ['test_20mode_20_3a_20b_20usart_20server_20b_4',['Test Mode : &lt;b&gt;USART Server&lt;/b&gt;',['../group__dv__usart.html#autotoc_md14',1,'']]],
  ['testing_5',['Socket testing',['../group__wifi__sock__testing.html',1,'']]],
  ['tests_6',['Tests',['../group__can__tests.html',1,'Tests'],['../group__eth__tests.html',1,'Tests'],['../group__gpio__tests.html',1,'Tests'],['../group__i2c__tests.html',1,'Tests'],['../group__mci__tests.html',1,'Tests'],['../group__spi__tests.html',1,'Tests'],['../group__usart__tests.html',1,'Tests'],['../group__usbd__tests.html',1,'Tests'],['../group__usbh__tests.html',1,'Tests'],['../group__wifi__tests.html',1,'Tests'],['../group__usbd__comp__test.html',1,'USB Compliance Tests']]],
  ['tests_20in_20appropriate_20strong_20dv_5f_20_5fconfig_20h_20strong_20file_7',['Step 7: Configure the Driver Tests in appropriate &lt;strong&gt;DV_..._Config.h&lt;/strong&gt; file.',['../setup.html#autotoc_md6',1,'']]],
  ['that_20provides_20strong_20required_20cmsis_20driver_20strong_20click_20strong_20ok_20strong_8',['Step 5: Select the &lt;strong&gt;Board Layer&lt;/strong&gt; that provides &lt;strong&gt;required CMSIS Driver&lt;/strong&gt;, click &lt;strong&gt;OK&lt;/strong&gt;.',['../setup.html#autotoc_md4',1,'']]],
  ['the_20application_9',['Step 9: Build and Run the application',['../setup.html#autotoc_md8',1,'']]],
  ['the_20bsd_20strict_20specification_10',['WiFi socket deviations from the BSD-strict specification',['../group__wifi__sock__testing.html#autotoc_md9',1,'']]],
  ['the_20driver_20tests_20in_20appropriate_20strong_20dv_5f_20_5fconfig_20h_20strong_20file_11',['Step 7: Configure the Driver Tests in appropriate &lt;strong&gt;DV_..._Config.h&lt;/strong&gt; file.',['../setup.html#autotoc_md6',1,'']]],
  ['the_20required_20hardware_12',['Step 8: Setup the required hardware',['../setup.html#autotoc_md7',1,'']]],
  ['the_20strong_20board_20layer_20strong_20that_20provides_20strong_20required_20cmsis_20driver_20strong_20click_20strong_20ok_20strong_13',['Step 5: Select the &lt;strong&gt;Board Layer&lt;/strong&gt; that provides &lt;strong&gt;required CMSIS Driver&lt;/strong&gt;, click &lt;strong&gt;OK&lt;/strong&gt;.',['../setup.html#autotoc_md4',1,'']]],
  ['the_20strong_20cmsis_20strong_20extension_20click_20strong_20create_20a_20new_20solution_20strong_14',['Step 1: In the &lt;strong&gt;CMSIS&lt;/strong&gt; extension, click &lt;strong&gt;Create a New Solution&lt;/strong&gt;.',['../setup.html#autotoc_md0',1,'']]],
  ['the_20strong_20manage_20solution_20strong_20under_20strong_20build_20type_20strong_20select_20desired_20driver_20for_20validation_20click_20strong_20save_20strong_15',['Step 6: In the &lt;strong&gt;Manage Solution&lt;/strong&gt;, under &lt;strong&gt;Build Type&lt;/strong&gt; select desired Driver for validation, click &lt;strong&gt;Save&lt;/strong&gt;.',['../setup.html#autotoc_md5',1,'']]],
  ['the_20strong_20target_20board_20strong_16',['Step 2: Select the &lt;strong&gt;Target Board&lt;/strong&gt;.',['../setup.html#autotoc_md1',1,'']]],
  ['troubleshooting_17',['Troubleshooting',['../group__spi__server.html#spi_server_troubleshooting',1,'Troubleshooting'],['../group__usart__server.html#usart_server_troubleshooting',1,'Troubleshooting'],['../group__wifi__sock__setup.html#sockserver_pc_win_troubleshooting',1,'Troubleshooting']]],
  ['type_20strong_20select_20desired_20driver_20for_20validation_20click_20strong_20save_20strong_18',['Step 6: In the &lt;strong&gt;Manage Solution&lt;/strong&gt;, under &lt;strong&gt;Build Type&lt;/strong&gt; select desired Driver for validation, click &lt;strong&gt;Save&lt;/strong&gt;.',['../setup.html#autotoc_md5',1,'']]]
];
