/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.11.0
 *
 * Project: 'USART_Server.Release+STM32F429ZITx' 
 * Target:  'Release+STM32F429ZITx' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* Keil::Device:STM32Cube HAL:Common@1.7.13 */
#define USE_HAL_DRIVER


#endif /* PRE_INCLUDE_GLOBAL_H */
