/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.11.0
 *
 * Project: 'SPI_Server.Debug+STM32F429ZITx' 
 * Target:  'Debug+STM32F429ZITx' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* Keil::Device:STM32Cube HAL:Common@1.7.13 */
#define USE_HAL_DRIVER


#endif /* PRE_INCLUDE_GLOBAL_H */
