/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define IOCON_PIO_DIGITAL_EN 0x0100u  /*!<@brief Enables digital function */
#define IOCON_PIO_FUNC1 0x01u         /*!<@brief Selects pin function 1 */
#define IOCON_PIO_INV_DI 0x00u        /*!<@brief Input function is not inverted */
#define IOCON_PIO_MODE_INACT 0x00u    /*!<@brief No addition pin function */
#define IOCON_PIO_OPENDRAIN_DI 0x00u  /*!<@brief Open drain is disabled */
#define IOCON_PIO_SLEW_STANDARD 0x00u /*!<@brief Standard mode, output slew rate control is enabled */

/*! @name FC0_RXD_SDA_MOSI_DATA (number 92), P8[2]/U6[13]/FC0_USART_RXD
  @{ */
/* @} */

/*! @name FC0_TXD_SCL_MISO_WS (number 94), P8[3]/U6[12]/FC0_USART_TXD
  @{ */
/* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitDEBUG_UARTPins(void); /* Function assigned for the Cortex-M33 (Core #0) */

#define IOCON_PIO_ASW_DIS_DI 0x00u    /*!<@brief Analog switch is disabled */
#define IOCON_PIO_ASW_EN 0x00u        /*!<@brief Analog switch is enabled */
#define IOCON_PIO_DIGITAL_EN 0x0100u  /*!<@brief Enables digital function */
#define IOCON_PIO_FUNC6 0x06u         /*!<@brief Selects pin function 6 */
#define IOCON_PIO_INV_DI 0x00u        /*!<@brief Input function is not inverted */
#define IOCON_PIO_MODE_INACT 0x00u    /*!<@brief No addition pin function */
#define IOCON_PIO_MODE_PULLDOWN 0x10u /*!<@brief Selects pull-down function */
#define IOCON_PIO_MODE_PULLUP 0x20u   /*!<@brief Selects pull-up function */
#define IOCON_PIO_OPENDRAIN_DI 0x00u  /*!<@brief Open drain is disabled */
#define IOCON_PIO_SLEW_STANDARD 0x00u /*!<@brief Standard mode, output slew rate control is enabled */

/*! @name SWCLK (number 13), U14[4]/SWDCLK_TRGT
  @{ */
/* @} */

/*! @name SWDIO (number 12), U15[4]/D7/P7[2]/IF_SWDIO
  @{ */
/* @} */

/*! @name SWO (number 21), U14[12]/SWO_TRGT
  @{ */
/* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitSWD_DEBUGPins(void); /* Function assigned for the Cortex-M33 (Core #0) */

#define IOCON_PIO_DIGITAL_EN 0x0100u  /*!<@brief Enables digital function */
#define IOCON_PIO_FUNC7 0x07u         /*!<@brief Selects pin function 7 */
#define IOCON_PIO_INV_DI 0x00u        /*!<@brief Input function is not inverted */
#define IOCON_PIO_MODE_INACT 0x00u    /*!<@brief No addition pin function */
#define IOCON_PIO_OPENDRAIN_DI 0x00u  /*!<@brief Open drain is disabled */
#define IOCON_PIO_SLEW_STANDARD 0x00u /*!<@brief Standard mode, output slew rate control is enabled */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitUSBPins(void); /* Function assigned for the Cortex-M33 (Core #0) */

#define IOCON_PIO_DIGITAL_EN 0x0100u  /*!<@brief Enables digital function */
#define IOCON_PIO_FUNC0 0x00u         /*!<@brief Selects pin function 0 */
#define IOCON_PIO_INV_DI 0x00u        /*!<@brief Input function is not inverted */
#define IOCON_PIO_MODE_PULLUP 0x20u   /*!<@brief Selects pull-up function */
#define IOCON_PIO_OPENDRAIN_DI 0x00u  /*!<@brief Open drain is disabled */
#define IOCON_PIO_SLEW_STANDARD 0x00u /*!<@brief Standard mode, output slew rate control is enabled */

/*! @name PIO1_4 (number 1), R78/P18[5]/LEDR/PWM_ARD
  @{ */
#define BOARD_INITLEDSPINS_LED_BULE_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITLEDSPINS_LED_BULE_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_INITLEDSPINS_LED_BULE_PIN 4U    /*!<@brief 1U pin index: 4 */
                                              /* @} */

/*! @name PIO1_6 (number 5), R80/P18[9]/LEDB/PWM_ARD
  @{ */
#define BOARD_INITLEDSPINS_LED_RED_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITLEDSPINS_LED_RED_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_INITLEDSPINS_LED_RED_PIN 6U    /*!<@brief 1U pin index: 6 */
                                             /* @} */

/*! @name PIO1_7 (number 9), R79/[P18[7]/LEDG/PWM_ARD
  @{ */
#define BOARD_INITLEDSPINS_LED_GREEN_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITLEDSPINS_LED_GREEN_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_INITLEDSPINS_LED_GREEN_PIN 7U    /*!<@brief 1U pin index: 7 */
                                               /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitLEDsPins(void); /* Function assigned for the Cortex-M33 (Core #0) */

#define IOCON_PIO_ASW_EN 0x00u        /*!<@brief Analog switch is enabled */
#define IOCON_PIO_DIGITAL_EN 0x0100u  /*!<@brief Enables digital function */
#define IOCON_PIO_FUNC0 0x00u         /*!<@brief Selects pin function 0 */
#define IOCON_PIO_INV_DI 0x00u        /*!<@brief Input function is not inverted */
#define IOCON_PIO_MODE_PULLUP 0x20u   /*!<@brief Selects pull-up function */
#define IOCON_PIO_OPENDRAIN_DI 0x00u  /*!<@brief Open drain is disabled */
#define IOCON_PIO_SLEW_STANDARD 0x00u /*!<@brief Standard mode, output slew rate control is enabled */

/*! @name PIO0_5 (number 88), S1/J10[1]/U3[12]/P17[8]/P7[7]/U11[4]/P0_5-ISP1
  @{ */
#define BOARD_INITBUTTONSPINS_S1_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITBUTTONSPINS_S1_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_INITBUTTONSPINS_S1_PIN 5U    /*!<@brief 0U pin index: 5 */
                                           /* @} */

/*! @name PIO1_9 (number 10), S3/P18[1]/PIO1_9_GPIO_ARD
  @{ */
#define BOARD_INITBUTTONSPINS_S3_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITBUTTONSPINS_S3_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_INITBUTTONSPINS_S3_PIN 9U    /*!<@brief 1U pin index: 9 */
                                           /* @} */

/*! @name PIO0_18 (number 56), P18[20]/PIO0_18_GPIO_ARD
  @{ */
#define BOARD_INITBUTTONSPINS_S2_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITBUTTONSPINS_S2_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_INITBUTTONSPINS_S2_PIN 18U   /*!<@brief 0U pin index: 18 */
                                           /* @} */

/*! @name RESETN (number 32), S4
  @{ */
/* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitBUTTONsPins(void); /* Function assigned for the Cortex-M33 (Core #0) */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins_Core0(void); /* Function assigned for the Cortex-M33 (Core #0) */

#define IOCON_PIO_ASW_DIS_EN 0x0400u  /*!<@brief Analog switch is enabled */
#define IOCON_PIO_DIGITAL_EN 0x0100u  /*!<@brief Enables digital function */
#define IOCON_PIO_FUNC1 0x01u         /*!<@brief Selects pin function 1 */
#define IOCON_PIO_FUNC2 0x02u         /*!<@brief Selects pin function 2 */
#define IOCON_PIO_FUNC5 0x05u         /*!<@brief Selects pin function 5 */
#define IOCON_PIO_FUNC7 0x07u         /*!<@brief Selects pin function 7 */
#define IOCON_PIO_INV_DI 0x00u        /*!<@brief Input function is not inverted */
#define IOCON_PIO_MODE_INACT 0x00u    /*!<@brief No addition pin function */
#define IOCON_PIO_MODE_PULLUP 0x20u   /*!<@brief Selects pull-up function */
#define IOCON_PIO_OPENDRAIN_DI 0x00u  /*!<@brief Open drain is disabled */
#define IOCON_PIO_SLEW_STANDARD 0x00u /*!<@brief Standard mode, output slew rate control is enabled */

/*! @name FC4_TXD_SCL_MISO_WS (number 4), P17[1]/P24[5]/FC4_I2C_SCL_ARD
  @{ */
/* @} */

/*! @name FC4_RXD_SDA_MOSI_DATA (number 30), P17[3]/P24[6]/FC4_I2C_SDA_ARD
  @{ */
/* @} */

/*! @name MCLK (number 91), P19[7]/P19[8]/PLU_IN0/GPIO
  @{ */
/* @} */

/*! @name FC7_SCK (number 76), P17[14]/FC7_I2S_SCK
  @{ */
/* @} */

/*! @name FC7_RXD_SDA_MOSI_DATA (number 74), P17[10]/FC7_I2S_TX
  @{ */
/* @} */

/*! @name FC7_TXD_SCL_MISO_WS (number 90), P17[12]/FC7_I2S_WS
  @{ */
/* @} */

/*! @name FC6_SCK (number 21), U14[12]/SWO_TRGT
  @{ */
/* @} */

/*! @name FC6_RXD_SDA_MOSI_DATA (number 2), P17[20]/FC6_I2S_RX
  @{ */
/* @} */

/*! @name FC6_TXD_SCL_MISO_WS (number 87), P18[17]/SD1_PWR_EN
  @{ */
/* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitI2SPins(void); /* Function assigned for the Cortex-M33 (Core #0) */

#define IOCON_PIO_ASW_DIS_DI 0x00u    /*!<@brief Analog switch is disabled */
#define IOCON_PIO_DIGITAL_EN 0x0100u  /*!<@brief Enables digital function */
#define IOCON_PIO_FUNC0 0x00u         /*!<@brief Selects pin function 0 */
#define IOCON_PIO_FUNC5 0x05u         /*!<@brief Selects pin function 5 */
#define IOCON_PIO_INV_DI 0x00u        /*!<@brief Input function is not inverted */
#define IOCON_PIO_MODE_INACT 0x00u    /*!<@brief No addition pin function */
#define IOCON_PIO_MODE_PULLUP 0x20u   /*!<@brief Selects pull-up function */
#define IOCON_PIO_OPENDRAIN_DI 0x00u  /*!<@brief Open drain is disabled */
#define IOCON_PIO_SLEW_STANDARD 0x00u /*!<@brief Standard mode, output slew rate control is enabled */

/*! @name FC4_RXD_SDA_MOSI_DATA (number 30), P17[3]/P24[6]/FC4_I2C_SDA_ARD
  @{ */
/* @} */

/*! @name FC4_TXD_SCL_MISO_WS (number 4), P17[1]/P24[5]/FC4_I2C_SCL_ARD
  @{ */
/* @} */

/*! @name PIO1_19 (number 58), U7[3]/P18[14]/PLU_OUT1/GPIO
  @{ */
#define BOARD_INITACCELPINS_ACCL_INTR_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITACCELPINS_ACCL_INTR_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_INITACCELPINS_ACCL_INTR_PIN 19U   /*!<@brief 1U pin index: 19 */
                                                /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitACCELPins(void); /* Function assigned for the Cortex-M33 (Core #0) */

#define IOCON_PIO_ASW_DIS_DI 0x00u     /*!<@brief Analog switch is disabled */
#define IOCON_PIO_DIGITAL_EN 0x0100u   /*!<@brief Enables digital function */
#define IOCON_PIO_FUNC6 0x06u          /*!<@brief Selects pin function 6 */
#define IOCON_PIO_INV_DI 0x00u         /*!<@brief Input function is not inverted */
#define IOCON_PIO_MODE_INACT 0x00u     /*!<@brief No addition pin function */
#define IOCON_PIO_OPENDRAIN_DI 0x00u   /*!<@brief Open drain is disabled */
#define IOCON_PIO_SLEW_STANDARD 0x00u  /*!<@brief Standard mode, output slew rate control is enabled */
#define PIO0_27_DIGIMODE_DIGITAL 0x01u /*!<@brief Select Digital mode.: Digital mode, digital input is enabled. */
#define PIO0_27_FUNC_ALT1 0x01u        /*!<@brief Selects pin function.: Alternative connection 1. */
#define PIO1_24_DIGIMODE_DIGITAL 0x01u /*!<@brief Select Digital mode.: Digital mode, digital input is enabled. */
#define PIO1_24_FUNC_ALT1 0x01u        /*!<@brief Selects pin function.: Alternative connection 1. */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void); /* Function assigned for the Cortex-M33 (Core #0) */

/*!
 * @brief Select Digital mode.: Digital mode, digital input is enabled. */
#define PIO0_26_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief
 * Driver slew rate.
 * : Fast mode, slew rate control is disabled.
 * Refer to the appropriate specific device data sheet for details.
 */
#define PIO0_26_SLEW_FAST 0x01u
/*!
 * @brief Select Digital mode.: Digital mode, digital input is enabled. */
#define PIO1_1_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_1_FUNC_ALT0 0x00u
/*!
 * @brief
 * Driver slew rate.
 * : Fast mode, slew rate control is disabled.
 * Refer to the appropriate specific device data sheet for details.
 */
#define PIO1_1_SLEW_FAST 0x01u
/*!
 * @brief Select Digital mode.: Digital mode, digital input is enabled. */
#define PIO1_2_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 6. */
#define PIO1_2_FUNC_ALT6 0x06u
/*!
 * @brief
 * Driver slew rate.
 * : Fast mode, slew rate control is disabled.
 * Refer to the appropriate specific device data sheet for details.
 */
#define PIO1_2_SLEW_FAST 0x01u
/*!
 * @brief Select Digital mode.: Digital mode, digital input is enabled. */
#define PIO1_3_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 6. */
#define PIO1_3_FUNC_ALT6 0x06u
/*!
 * @brief
 * Driver slew rate.
 * : Fast mode, slew rate control is disabled.
 * Refer to the appropriate specific device data sheet for details.
 */
#define PIO1_3_SLEW_FAST 0x01u
/*!
 * @brief Select Digital mode.: Digital mode, digital input is enabled. */
#define PIO1_5_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_5_FUNC_ALT0 0x00u

/*! @name HS_SPI_SCK (number 61), P17[9]/P23[4]/LSPI_HS_SCK
  @{ */
/* @} */

/*! @name HS_SPI_MISO (number 62), P17[11]/P23[5]/LSPI_HS_MISO
  @{ */
/* @} */

/*! @name HS_SPI_MOSI (number 60), P17[13]/P23[6]/LSPI_HS_MOSI
  @{ */
/* @} */

/*! @name PIO1_1 (number 59), P17[15]/P23[3]/LSPI_HS_SSEL1
  @{ */
#define BOARD_INITPINS_ISM43362_ISMART43362_SSN_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_ISM43362_ISMART43362_SSN_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_INITPINS_ISM43362_ISMART43362_SSN_PIN 1U    /*!<@brief 1U pin index: 1 */
                                                          /* @} */

/*! @name PIO1_5 (number 31), P17[17]/P24[1]/PIO1_5_GPIO_ARD
  @{ */
#define BOARD_INITPINS_ISM43362_ISMART43362_DATARDY_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_ISM43362_ISMART43362_DATARDY_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_INITPINS_ISM43362_ISMART43362_DATARDY_PIN 5U    /*!<@brief 1U pin index: 5 */
                                                              /* @} */

/*!
 * @brief Initialize pins for ISMART43362-E WiFi module using Arduino header.
 * SPI SCK    = P1_2
 * SPI MISO = P1_3
 * SPI 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * MOSI = P0_26
 * SPI SSN    = P1_1
 * DATARDY = P1_5
 *
 */
void BOARD_InitPins_ISM43362(void); /* Function assigned for the Cortex-M33 (Core #0) */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
